"use client";

import { useEffect, useMemo, useState } from "react";
import rawNews from "../../data/news.json";
import rawAnnouncements from "../../data/announcements.json";

// Three separate things, as asked for, because they answer different
// questions: "what can I apply to", "what's worth reading", and "what
// changed on the site".
//
// Jobs and articles are regenerated by news_scraper.py and read from a
// static file — the same shape as the interview-questions scraper. Nothing
// is fetched in the request path, so a slow or down third-party API can
// never make this page hang; the trade-off is that freshness is whenever
// the scraper was last run.

type Job = {
  id: string; title: string; firm: string; location: string;
  url: string; postedAt: string | null; category: string;
};
type Article = {
  id: string; title: string; url: string; source: string;
  summary: string; publishedAt: string | null; topic: string;
};
type Announcement = {
  id: string; date: string; kind: string; title: string;
  body: string; code?: string; active: boolean;
};

// The bundled file is a fallback snapshot, not the live feed. The daily
// cron writes to D1 and /api/news serves that; this is what shows on a
// first deploy, or if the cron has not run yet, so the page is never empty.
const fallback = rawNews as { generatedAt: string; jobs: Job[]; articles: Article[] };
const announcements = (rawAnnouncements as { announcements: Announcement[] }).announcements;

type Tab = "jobs" | "reading" | "site";

const JOB_FILTERS = [
  { id: "all", label: "All" },
  { id: "trading", label: "Trading" },
  { id: "research", label: "Research" },
  { id: "engineering", label: "Engineering" },
  { id: "risk", label: "Risk" },
  { id: "internship", label: "Internships" },
] as const;

/**
 * 2-3 letter mark for a firm, so an opening reads as a cabinet plate.
 *
 * Naive initials get this wrong in both directions: "IMC Trading" is not
 * "IT" (IMC is already the mark) and "WorldQuant" is not "WOR" (the capitals
 * carry it). So an existing acronym wins, then internal capitals, then
 * initials, then a truncation.
 */
function firmMark(firm: string): string {
  const words = firm.replace(/[^A-Za-z ]/g, "").trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) return firm.slice(0, 3).toUpperCase();

  // Already an acronym — "IMC", "SIG", "DRW", "XTX".
  if (/^[A-Z]{2,4}$/.test(words[0])) return words[0];

  // CamelCase compound — "WorldQuant" -> "WQ".
  const caps = words[0].match(/[A-Z]/g);
  if (words.length === 1 && caps && caps.length >= 2) return caps.slice(0, 3).join("");

  if (words.length >= 2) return (words[0][0] + words[1][0]).toUpperCase();
  return words[0].slice(0, 3).toUpperCase();
}

/** "3 days ago" reads faster than a date when scanning for what's new. */
function timeAgo(iso: string | null): string {
  if (!iso) return "";
  const then = new Date(iso).getTime();
  if (!Number.isFinite(then)) return "";
  const days = Math.floor((Date.now() - then) / 86_400_000);
  if (days <= 0) return "today";
  if (days === 1) return "yesterday";
  if (days < 30) return `${days}d ago`;
  if (days < 365) return `${Math.floor(days / 30)}mo ago`;
  return `${Math.floor(days / 365)}y ago`;
}

export default function NewsBoard() {
  const [tab, setTab] = useState<Tab>("jobs");
  const [jobFilter, setJobFilter] = useState<string>("all");
  const [firm, setFirm] = useState<string>("all");
  const [news, setNews] = useState(fallback);
  const [isLive, setIsLive] = useState(false);

  // Swap in the cron-refreshed feed once it arrives. Deliberately starts
  // from the bundled snapshot so the page renders immediately and still
  // works if the request fails.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch("/api/news");
        const data = (await res.json()) as {
          generatedAt: string | null; jobs: Job[]; articles: Article[]; stale: boolean;
        };
        if (cancelled || data.stale || !data.jobs.length) return;
        setNews({ generatedAt: data.generatedAt ?? fallback.generatedAt, jobs: data.jobs, articles: data.articles });
        setIsLive(true);
      } catch {
        /* keep the bundled snapshot */
      }
    })();
    return () => { cancelled = true; };
  }, []);

  const firms = useMemo(
    () => [...new Set(news.jobs.map((j) => j.firm))].sort(),
    [news],
  );

  const visibleJobs = useMemo(
    () =>
      news.jobs.filter(
        (j) =>
          (jobFilter === "all" || j.category === jobFilter) &&
          (firm === "all" || j.firm === firm),
      ),
    [news, jobFilter, firm],
  );

  const liveAnnouncements = announcements.filter((a) => a.active);

  // Ticker copy comes from the same openings the board lists — a short slice,
  // since the track is rendered twice and a long list makes the loop crawl.
  const tickerItems = useMemo(
    () => news.jobs.slice(0, 12).map((j) => `// ${firmMark(j.firm)} · ${j.title}`),
    [news],
  );

  return (
    <div className="answer-content news-board">
      <section className="arc-hero" aria-label="Latest openings">
        <div className="arc-ticker-bar">
          {/* Only claim "live" when /api/news actually answered with fresh
              data — the bundled snapshot says so instead. */}
          {isLive ? (
            <span className="arc-live-dot">&#9679; LIVE</span>
          ) : (
            <span className="arc-snapshot-chip">SNAPSHOT</span>
          )}
          <div className="arc-ticker-window">
            {/* Rendered twice so translateX(-50%) loops without a seam. */}
            <div className="arc-ticker-track" aria-hidden="true">
              {[...tickerItems, ...tickerItems].map((t, i) => (
                <span key={i}>{t}</span>
              ))}
            </div>
          </div>
        </div>
        <div className="arc-hero-body">
          <p className="arc-eyebrow">Bulletin board // refreshed {timeAgo(news.generatedAt) || "recently"}</p>
          <h1 className="arc-hero-title" style={{ marginBottom: 0 }}>News</h1>
        </div>
      </section>

      <div className="arc-chip-row" role="tablist">
        {([
          ["jobs", `Jobs (${news.jobs.length})`],
          ["reading", `Reading (${news.articles.length})`],
          ["site", `Site (${liveAnnouncements.length})`],
        ] as [Tab, string][]).map(([id, label]) => (
          <button
            key={id}
            type="button"
            role="tab"
            aria-selected={tab === id}
            className={tab === id ? "arc-chip is-on" : "arc-chip"}
            onClick={() => setTab(id)}
          >
            {label}
          </button>
        ))}
      </div>

      {tab === "jobs" && (
        <>
          <div className="arc-news-filters">
            {JOB_FILTERS.map((f) => (
              <button
                key={f.id}
                type="button"
                className={jobFilter === f.id ? "arc-news-chip is-on" : "arc-news-chip"}
                onClick={() => setJobFilter(f.id)}
              >
                {f.label}
              </button>
            ))}
          </div>

          <label className="news-firm-select">
            <span>Firm</span>
            <select value={firm} onChange={(e) => setFirm(e.target.value)}>
              <option value="all">All firms</option>
              {firms.map((f) => (
                <option key={f} value={f}>{f}</option>
              ))}
            </select>
          </label>

          <p className="news-count">
            {visibleJobs.length} opening{visibleJobs.length === 1 ? "" : "s"}
          </p>

          <div className="arc-open-list">
            {visibleJobs.slice(0, 120).map((j) => {
              const age = timeAgo(j.postedAt);
              const fresh = age === "today" || age === "yesterday";
              return (
                /* Third-party destination: noopener/noreferrer so the target
                   can't reach back through window.opener. */
                <a key={j.id} href={j.url} target="_blank" rel="noopener noreferrer" className="arc-open">
                  <span className="arc-open-mark" aria-hidden="true">{firmMark(j.firm)}</span>
                  <span style={{ minWidth: 0 }}>
                    <strong className="arc-open-title">{j.title}</strong>
                    <span className="arc-open-meta">
                      {j.firm} &middot; {j.location} &middot; {j.category}
                    </span>
                  </span>
                  <span className="arc-open-side">
                    {age && <span className={fresh ? "arc-age is-fresh" : "arc-age"}>{age}</span>}
                    <span className="arc-open-apply">Apply &rarr;</span>
                  </span>
                </a>
              );
            })}
          </div>
          {visibleJobs.length > 120 && (
            <p className="news-count">Showing the 120 newest. Narrow by firm or category to see more.</p>
          )}
          {visibleJobs.length === 0 && <p className="news-empty">Nothing matches that filter right now.</p>}
        </>
      )}

      {tab === "reading" && (
        <div className="arc-read-grid">
          {news.articles.map((a) => (
            <a key={a.id} href={a.url} target="_blank" rel="noopener noreferrer" className="arc-read">
              <span className="arc-read-topic">{a.topic}</span>
              <strong className="arc-read-title">{a.title}</strong>
              {a.summary && <span className="arc-read-summary">{a.summary}</span>}
              <span className="arc-read-source">
                {a.source}
                {timeAgo(a.publishedAt) ? ` \u00b7 ${timeAgo(a.publishedAt)}` : ""}
              </span>
            </a>
          ))}
        </div>
      )}

      {tab === "site" && (
        <div className="arc-note-list">
          {liveAnnouncements.map((a) => (
            <div key={a.id} className="arc-site-note">
              <span className={`arc-kind is-${a.kind.toLowerCase()}`}>{a.kind}</span>
              <span>
                <strong className="arc-open-title">{a.title}</strong>
                <span className="arc-read-summary">{a.body}</span>
                {a.code && (
                  <span className="news-code">
                    CODE <strong>{a.code}</strong>
                  </span>
                )}
                <span className="arc-read-source">{a.date}</span>
              </span>
            </div>
          ))}
          {liveAnnouncements.length === 0 && <p className="arc-note">No site news right now.</p>}
        </div>
      )}

      <p className="arc-note">
        Jobs and reading last refreshed {timeAgo(news.generatedAt)}
        {isLive ? " by the daily job." : " (built-in snapshot)."} Openings come straight from each firm&rsquo;s own
        careers board.
      </p>
    </div>
  );
}
