"use client";

import { useMemo, useState } from "react";
import rawNews from "../../data/news.json";
import rawAnnouncements from "../../data/announcements.json";

// Three separate things, as asked for, because they answer different
// questions: "what can I apply to", "what's worth reading", and "what
// changed on the site".
//
// Jobs and articles are regenerated by news_scraper.py and read from a
// static file — the same shape as the interview-questions scraper. Nothing
// is fetched in the request path, so a slow or down third-party API can
// never make this page hang; the trade-off is that freshness is whenever
// the scraper was last run.

type Job = {
  id: string; title: string; firm: string; location: string;
  url: string; postedAt: string | null; category: string;
};
type Article = {
  id: string; title: string; url: string; source: string;
  summary: string; publishedAt: string | null; topic: string;
};
type Announcement = {
  id: string; date: string; kind: string; title: string;
  body: string; code?: string; active: boolean;
};

const news = rawNews as { generatedAt: string; jobs: Job[]; articles: Article[] };
const announcements = (rawAnnouncements as { announcements: Announcement[] }).announcements;

type Tab = "jobs" | "reading" | "site";

const JOB_FILTERS = [
  { id: "all", label: "All" },
  { id: "trading", label: "Trading" },
  { id: "research", label: "Research" },
  { id: "engineering", label: "Engineering" },
  { id: "risk", label: "Risk" },
  { id: "internship", label: "Internships" },
] as const;

/** "3 days ago" reads faster than a date when scanning for what's new. */
function timeAgo(iso: string | null): string {
  if (!iso) return "";
  const then = new Date(iso).getTime();
  if (!Number.isFinite(then)) return "";
  const days = Math.floor((Date.now() - then) / 86_400_000);
  if (days <= 0) return "today";
  if (days === 1) return "yesterday";
  if (days < 30) return `${days}d ago`;
  if (days < 365) return `${Math.floor(days / 30)}mo ago`;
  return `${Math.floor(days / 365)}y ago`;
}

export default function NewsBoard() {
  const [tab, setTab] = useState<Tab>("jobs");
  const [jobFilter, setJobFilter] = useState<string>("all");
  const [firm, setFirm] = useState<string>("all");

  const firms = useMemo(
    () => [...new Set(news.jobs.map((j) => j.firm))].sort(),
    [],
  );

  const visibleJobs = useMemo(
    () =>
      news.jobs.filter(
        (j) =>
          (jobFilter === "all" || j.category === jobFilter) &&
          (firm === "all" || j.firm === firm),
      ),
    [jobFilter, firm],
  );

  const liveAnnouncements = announcements.filter((a) => a.active);

  return (
    <div className="answer-content news-board">
      <p className="pirate-kicker">Outcry</p>
      <h1 className="pirate-story-line answer-title">News</h1>

      <div className="news-tabs" role="tablist">
        {([
          ["jobs", `Jobs (${news.jobs.length})`],
          ["reading", `Reading (${news.articles.length})`],
          ["site", `Site (${liveAnnouncements.length})`],
        ] as [Tab, string][]).map(([id, label]) => (
          <button
            key={id}
            type="button"
            role="tab"
            aria-selected={tab === id}
            className={tab === id ? "news-tab is-active" : "news-tab"}
            onClick={() => setTab(id)}
          >
            {label}
          </button>
        ))}
      </div>

      {tab === "jobs" && (
        <>
          <div className="news-filter-row">
            {JOB_FILTERS.map((f) => (
              <button
                key={f.id}
                type="button"
                className={jobFilter === f.id ? "news-chip is-active" : "news-chip"}
                onClick={() => setJobFilter(f.id)}
              >
                {f.label}
              </button>
            ))}
          </div>

          <label className="news-firm-select">
            <span>Firm</span>
            <select value={firm} onChange={(e) => setFirm(e.target.value)}>
              <option value="all">All firms</option>
              {firms.map((f) => (
                <option key={f} value={f}>{f}</option>
              ))}
            </select>
          </label>

          <p className="news-count">
            {visibleJobs.length} opening{visibleJobs.length === 1 ? "" : "s"}
          </p>

          <ul className="news-list">
            {visibleJobs.slice(0, 120).map((j) => (
              <li key={j.id} className="news-row">
                {/* Third-party destination: noopener/noreferrer so the target
                    can't reach back through window.opener. */}
                <a href={j.url} target="_blank" rel="noopener noreferrer" className="news-row-link">
                  <span className="news-row-title">{j.title}</span>
                  <span className="news-row-meta">
                    <span className="news-firm">{j.firm}</span>
                    <span className="news-loc">{j.location}</span>
                    <span className={`news-cat is-${j.category}`}>{j.category}</span>
                    <span className="news-age">{timeAgo(j.postedAt)}</span>
                  </span>
                </a>
              </li>
            ))}
          </ul>
          {visibleJobs.length > 120 && (
            <p className="news-count">Showing the 120 newest. Narrow by firm or category to see more.</p>
          )}
          {visibleJobs.length === 0 && <p className="news-empty">Nothing matches that filter right now.</p>}
        </>
      )}

      {tab === "reading" && (
        <ul className="news-list">
          {news.articles.map((a) => (
            <li key={a.id} className="news-row">
              <a href={a.url} target="_blank" rel="noopener noreferrer" className="news-row-link">
                <span className="news-row-title">{a.title}</span>
                {a.summary && <span className="news-row-summary">{a.summary}</span>}
                <span className="news-row-meta">
                  <span className="news-firm">{a.source}</span>
                  <span className={`news-cat is-${a.topic}`}>{a.topic}</span>
                  <span className="news-age">{timeAgo(a.publishedAt)}</span>
                </span>
              </a>
            </li>
          ))}
        </ul>
      )}

      {tab === "site" && (
        <ul className="news-list">
          {liveAnnouncements.map((a) => (
            <li key={a.id} className="news-row is-announcement">
              <span className="news-row-title">{a.title}</span>
              <span className="news-row-summary">{a.body}</span>
              {a.code && (
                <span className="news-code">
                  CODE <strong>{a.code}</strong>
                </span>
              )}
              <span className="news-row-meta">
                <span className={`news-cat is-${a.kind}`}>{a.kind}</span>
                <span className="news-age">{a.date}</span>
              </span>
            </li>
          ))}
          {liveAnnouncements.length === 0 && <p className="news-empty">No site news right now.</p>}
        </ul>
      )}

      <p className="news-generated">
        Jobs and reading last refreshed {timeAgo(news.generatedAt)}. Openings come straight from each firm&rsquo;s own
        careers board.
      </p>
    </div>
  );
}
